# Create image based on the official Node 6 image from dockerhub
FROM node:8

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Install dependecies
RUN npm install
RUN npm run build

WORKDIR /usr/src/app
# Get all the code needed to run the app
COPY . /usr/src/app



# Expose the port the app runs in
EXPOSE 8080
# Change directory so that our commands run inside this new directory
# Serve the app
CMD ["npm", "start"]